"""empty message

Revision ID: e25c600f7bfe
Revises: 
Create Date: 2023-12-15 10:47:06.507353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25c600f7bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debris',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('county_name', sa.String(length=255), nullable=True),
    sa.Column('geom_wkt', sa.Text(), nullable=True),
    sa.Column('kg_of_collected_waste', sa.Float(), nullable=True),
    sa.Column('others', sa.Float(), nullable=True),
    sa.Column('hygiene', sa.Float(), nullable=True),
    sa.Column('industrial', sa.Float(), nullable=True),
    sa.Column('fisheries', sa.Float(), nullable=True),
    sa.Column('personal_use', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debris')
    # ### end Alembic commands ###
